### ISSUE TITLE
Videos start normally and then "fade away"

### ISSUE THREAD

**Issue by Gyramuur** [kijai/ComfyUI-PyramidFlowWrapper#18]
I've been having this issue using the provided example workflows where videos seemingly start normally, and then they begin to lose detail until the final image is a blurry mess. 

I don't know if this is just the way PyramidFlow is, or if there's some sort of issue with the implementation.

https://github.com/user-attachments/assets/fbaa214b-da13-4ca2-a785-0235690c404b

https://github.com/user-attachments/assets/1cc7a6da-9e38-4ac1-908b-c49453cd56af

This also happens with I2V.

Here is a screenshot of my settings:

![image](https://github.com/user-attachments/assets/ff8c17c6-80f1-4da7-a5fa-1f93f8e11035)

**Comment by kijai** [comment]
Pretty much how the model is, some images work better than others, also the guidance scale affects it a lot, lower values seem to be able to create longer clips without fading out.

Overall the only good results I've got are with their example prompts, it would suggest the model is just undertrained, they have said they are training new one from scratch instead of continuing this SD3 version.

**Comment by Gyramuur** [comment]
> Pretty much how the model is, some images work better than others, also the guidance scale affects it a lot, lower values seem to be able to create longer clips without fading out.
> 
> Overall the only good results I've got are with their example prompts, it would suggest the model is just undertrained, they have said they are training new one from scratch instead of continuing this SD3 version.

Gotcha, thanks. :) I'll mark this as solved then.

**Comment by Kvento** [comment]
Yeah, it looks like the current model isn't that good yet. I can't wait for the creators to release a new model and training code and see how well the model can be retrained. 
If retraining the model works as well as, for example, retraining the SD1.5 and SDXL models, then the model could become the new Stable Diffusion in the world of video generation.

Because in some places even the current model produces pretty good results. And if it can be trained on... you know, specific data, then it will be a hit among those who stick to local generation.
